kernel:
  name: ZFlip3-KernelSU
  source: https://github.com/AlexFurina/android_kernel_samsung_sm8350.git
  branch: Flip3-Android16
  defconfig: vendor/b2q_kor_singlex_defconfig
  arch: arm64

toolchain:
  clang:
    repo: https://github.com/kdrag0n/proton-clang.git
    branch: master
    bin_path: bin

kernelsu:
  enable: true
  branch: main

anykernel:
  enable: true
  repo: https://github.com/osm0sis/AnyKernel3.git
  branch: master
